export { Dashboard } from './Dashboard'
export { StrategiesPage } from './Strategies'
export { StrategyDetailPage } from './StrategyDetail'
export { default as StrategyBuilderPage } from './StrategyBuilder'
export { BacktestsPage } from './Backtests'
export { BacktestReportPage } from './BacktestReport'
export { BacktestTradesPage } from './BacktestTrades'
export { ComparePage } from './Compare'
export { ChartPage } from './Chart'
export { RobustnessPage } from './Robustness'
export { SettingsPage } from './Settings'
